/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    FnButton: typeof import('fusion-ui-vue/components/index')['FnButton']
    FnDialog: typeof import('fusion-ui-vue/components/index')['FnDialog']
    FnInput: typeof import('fusion-ui-vue/components/index')['FnInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
