import type { Typography } from './typography'

const typography: Typography = {
  h1: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '57px',
    fontStyle: 'unset',
    letterSpacing: '-0.25px',
    lineHeight: '64px',
    textTransform: 'unset',
    textDecoration: 'unset',
  },
  h2: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '45px',
    fontStyle: 'unset',
    letterSpacing: '0px',
    lineHeight: '52px',
    textTransform: 'unset',
    textDecoration: 'unset',
  },
  h3: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '36px',
    fontStyle: 'unset',
    letterSpacing: '0px',
    lineHeight: '44px',
    textTransform: 'unset',
    textDecoration: 'unset',
  },
  h4: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '32px',
    fontStyle: 'unset',
    letterSpacing: '0px',
    lineHeight: '40px',
    textTransform: 'unset',
    textDecoration: 'unset',
  },
  h5: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '28px',
    fontStyle: 'unset',
    letterSpacing: '0px',
    lineHeight: '36px',
    textTransform: 'unset',
    textDecoration: 'unset',
  },
  h6: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '24px',
    fontStyle: 'unset',
    letterSpacing: '0px',
    lineHeight: '32px',
    textTransform: 'unset',
    textDecoration: 'unset',
  },
  title: {
    small: {
      fontFamily: 'Roboto',
      fontWeight: 500,
      fontSize: '14px',
      fontStyle: 'unset',
      letterSpacing: '0.1px',
      lineHeight: '20px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
    medium: {
      fontFamily: 'Roboto',
      fontWeight: 500,
      fontSize: '16px',
      fontStyle: 'unset',
      letterSpacing: '0.15000001px',
      lineHeight: '24px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
    large: {
      fontFamily: 'Roboto',
      fontWeight: 400,
      fontSize: '22px',
      fontStyle: 'unset',
      letterSpacing: '0px',
      lineHeight: '28px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
  },
  body: {
    small: {
      fontFamily: 'Roboto',
      fontWeight: 400,
      fontSize: '12px',
      fontStyle: 'unset',
      letterSpacing: '0.40000001px',
      lineHeight: '16px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
    medium: {
      fontFamily: 'Roboto',
      fontWeight: 400,
      fontSize: '14px',
      fontStyle: 'unset',
      letterSpacing: '0.25px',
      lineHeight: '20px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
    large: {
      fontFamily: 'Roboto',
      fontWeight: 400,
      fontSize: '16px',
      fontStyle: 'unset',
      letterSpacing: '0.5px',
      lineHeight: '24px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
  },
  label: {
    small: {
      fontFamily: 'Roboto',
      fontWeight: 500,
      fontSize: '11px',
      fontStyle: 'unset',
      letterSpacing: '0.5px',
      lineHeight: '16px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
    medium: {
      fontFamily: 'Roboto',
      fontWeight: 400,
      fontSize: '12px',
      fontStyle: 'unset',
      letterSpacing: '0.5px',
      lineHeight: '16px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
    large: {
      fontFamily: 'Roboto',
      fontWeight: 500,
      fontSize: '14px',
      fontStyle: 'unset',
      letterSpacing: '0.1px',
      lineHeight: '20px',
      textTransform: 'unset',
      textDecoration: 'unset',
    },
  },
}

export default typography
