/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PlAlert: typeof import('fusion-ui')['PlAlert']
    PlBadge: typeof import('fusion-ui')['PlBadge']
    PlButton: typeof import('fusion-ui/components/index')['PlButton']
    PlButtonGroup: typeof import('fusion-ui/components/index')['PlButtonGroup']
    PlIcon: typeof import('fusion-ui/components/index')['PlIcon']
    PlModal: typeof import('fusion-ui')['PlModal']
    PlTag: typeof import('fusion-ui')['PlTag']
  }
}
