/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InButton: typeof import('interface-ui/components/index')['InButton']
    InInput: typeof import('interface-ui/components/index')['InInput']
    InDialog: typeof import('interface-ui/components/index')['InDialog']
    InRadio: typeof import('interface-ui/components/index')['InRadio']
  }
}

declare module '@interface-ui/icons/*' {
  import Icon from '@interface-ui/icons/components/*.js'
  export default Icon
}
